<?php

/**
 * @file
 * Contains marketo.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function marketo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the marketo module.
    case 'help.page.marketo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Suite of modules providing integration with the Marketo email marketing platform.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Gets a SOAP exception error code.
 *
 * @see http://php.net/manual/en/class.soapfault.php
 */
function _marketo_soapfault_get_error_code(\SoapFault $e) {
  if (!empty($e->detail->serviceException->code)) {
    return $e->detail->serviceException->code;
  }
  return NULL;
}
